

    <div class="block newsletter">
        <p>Hello World!=)</p>
    </div>

<div id="one" class="foo">
    Hello World
</div>
<div id="two" class="foo">
    Cliked on me!

</div>



<div>
    <h5 class="custom-header">h5#selector</h5>
</div>


<script type="text/x-magento-init">
    {
        ".foo": {
            "Home_Jslearn/example":{
            "config": "value"
            }
        }
    }
</script>